### ISSUE TITLE
Dynamic Focusing

### ISSUE THREAD

**Issue by sim2kid** [sim2kid/Strange-Cargo#90]
**Is your feature request related to a problem? Please describe.**
You can't see distant objects in detail

**Describe the solution you'd like**
Adding dynamic focus. Have it based on the distance of the object at the center of the screen. After a certain distance, the focus should be disabled for distant objects. Closet objects can optionally be blurred as well when looking into the distance (if possible). This will be based on editing camera scripts.

**Comment by CharAznable1138** [comment]
Implemented 2/10/22
